### PR TITLE
Added the xDhcpServerClass to manage DHCP Server Classes

### PR DESCRIPTION
**Pull request by marciorschneider**
Hello, here is a resource to manage dhcp server classes.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xdhcpserver/35)

### CODE REVIEW

**Comment by marciorschneider** [comment]
Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdhcpserver/35)*

**Comment by marciorschneider** [comment]
Hello @RichardSiddaway, may you please review this pull request? Thank you.

**Comment by RichardSiddaway** [comment]
Reviewing

**Comment by RichardSiddaway** [comment]
Looks good to me

**Pull request merged**
